(WorkspaceName as text, WarehouseName as text, TableName as text, optional EmptyTableIfNotFound as table) as table =>
let
  Source = Fabric.Warehouse(null),
  #"Filtered rows" = Table.SelectRows(Source, each [workspaceName] = WorkspaceName),
  Custom = #"Filtered rows"{0}[Data],
  #"Filtered rows 1" = Table.SelectRows(Custom, each [displayName] = WarehouseName),
  #"Custom 1" = #"Filtered rows 1"{0}[Data],
  #"Filtered rows 2" = Table.SelectRows(#"Custom 1", each ([Schema] = "dbo")),
  #"Filtered rows 3" = Table.SelectRows(#"Filtered rows 2", each [Name] = TableName),
  #"Navigation 1" = if Table.RowCount(#"Filtered rows 3") = 0 then EmptyTableIfNotFound 
else #"Filtered rows 3"{0}[Data]
in
  #"Navigation 1"
