//fxExpandTableColumn
(myTable as table, tableFieldName as text) =>
let
  //myTable = "",
  Source = myTable,
  SourceTableFieldNames = Table.ColumnNames(Source),
  NestedTableFieldNames = Table.ColumnNames(Table.Column(myTable,tableFieldName){0}),
  AdjustedNestedTableFieldNames = List.Transform(NestedTableFieldNames,each if List.Contains(SourceTableFieldNames,_) then _ & ".1" else _),
  result = Table.ExpandTableColumn(Source, tableFieldName, NestedTableFieldNames, AdjustedNestedTableFieldNames)
in
  result
