//fxCompareLists
//2026-06-01 / B.Agullo / null-safe casing, deterministic pivot columns, typed output (Gen2-friendly)
//2025-12-19 / B.Agullo / added ignoreCasing optional parameter
//2025-11-14 / B.Agullo / compares two lists returning a table
(myList1 as list, myList2 as list, myList1Name as text, myList2Name as text, optional ignoreCasing as logical) as table =>
let
    ignoreCasingValue = ignoreCasing ?? true,

    normalize = (lst as list) as list =>
        List.Transform(lst, each
            if _ = null then null
            else if ignoreCasingValue then Text.Lower(Text.From(_))
            else Text.From(_)),

    list1 = normalize(myList1),
    list2 = normalize(myList2),

    table1 = Table.FromColumns(
        {list1, List.Repeat({myList1Name}, List.Count(list1))},
        type table [Value = text, Source = text]),
    table2 = Table.FromColumns(
        {list2, List.Repeat({myList2Name}, List.Count(list2))},
        type table [Value = text, Source = text]),

    combined  = Table.Distinct(Table.Combine({table1, table2})),
    withFlag  = Table.AddColumn(combined, "Flag", each 1, Int64.Type),

    // explicit column list -> deterministic schema for Gen2 staging
    pivoted   = Table.Pivot(withFlag, {myList1Name, myList2Name}, "Source", "Flag", List.Sum),

    withStatus = Table.AddColumn(pivoted, "Status", each
        if Record.Field(_, myList1Name) = Record.Field(_, myList2Name) then "OK"
        else if Record.Field(_, myList1Name) = null then myList2Name
        else if Record.Field(_, myList2Name) = null then myList1Name
        else "Error", type text),

    typed = Table.TransformColumnTypes(withStatus, {
        {"Value",       type text},
        {myList1Name,   Int64.Type},
        {myList2Name,   Int64.Type},
        {"Status",      type text}
    })
in
    typed
