// fxGetForeignKeyViolations
// Returns rows from sourceTable whose key value has no match in targetTable (left anti join).
// Optional info fields from both tables can be appended to the result for context.

(
    sourceTable          as table,
    targetTable          as table,
    sourceTableName      as text,
    targetTableName      as text,
    sourceTableField     as text,
    targetTableField     as text,
    optional sourceInfoFields        as list,   // extra columns from source to include in output
    optional targetInfoFields        as list,   // extra columns from target to include in output
    optional targetInfoRenamedFields as list    // renamed versions of targetInfoFields in output
) =>

let
    // -------------------------------------------------------------------------
    // TROUBLESHOOTING: To test this function interactively, comment out the
    // argument block above and uncomment the block below, then invoke the query.
    // -------------------------------------------------------------------------
    /*    
    sourceTable              = #"proposals_holded temp 10",
    targetTable              = Service,
    sourceTableName          = "proposals_holded",
    targetTableName          = "Service",
    sourceTableField         = "service_code",
    targetTableField         = "service_code",
    sourceInfoFields         = {"services"},
    targetInfoFields         = null, //{},
    targetInfoRenamedFields  = null, // {},
    */

    // -------------------------------------------------------------------------
    // Flags — used throughout to guard optional logic
    // -------------------------------------------------------------------------
    hasTargetInfoFields  = targetInfoRenamedFields <> null,
    hasSourceInfoFields  = sourceInfoFields <> null,

    // -------------------------------------------------------------------------
    // Snapshot of target info — grab the first row of the selected/renamed
    // target columns and store it as a record to stamp onto every violation row
    // -------------------------------------------------------------------------
    targetInfoRecord =
        if hasTargetInfoFields
        then Table.RenameColumns(
                 Table.SelectColumns(targetTable, targetInfoFields),
                 List.Zip({ targetInfoFields ?? {}, targetInfoRenamedFields ?? targetInfoFields ?? {} })
             ){0}
        else [],

    // -------------------------------------------------------------------------
    // Left anti join — keep only source rows with no matching key in target
    // -------------------------------------------------------------------------
    Violations = Table.NestedJoin(
        sourceTable, { sourceTableField },
        targetTable, { targetTableField },
        targetTableName,
        JoinKind.LeftAnti
    ),

    // -------------------------------------------------------------------------
    // Keep only the key column plus any requested source info columns
    // -------------------------------------------------------------------------
    KeyAndSourceInfo = Table.SelectColumns(
        Violations,
        { sourceTableField } & (sourceInfoFields ?? {})
    ),

    // -------------------------------------------------------------------------
    // Stamp target info onto every row (if requested)
    // -------------------------------------------------------------------------
    WithTargetInfoColumn =
        if hasTargetInfoFields
        then Table.AddColumn(KeyAndSourceInfo, "target_info_fields", each targetInfoRecord)
        else KeyAndSourceInfo,

    TargetInfoExpanded =
        if hasTargetInfoFields
        then Table.ExpandRecordColumn(
                 WithTargetInfoColumn,
                 "target_info_fields",
                 targetInfoRenamedFields ?? targetInfoFields ?? {},
                 targetInfoRenamedFields ?? targetInfoFields ?? {}
             )
        else WithTargetInfoColumn,

    TargetInfoTyped =
        if hasTargetInfoFields
        then Table.TransformColumnTypes(
                 TargetInfoExpanded,
                 List.Transform(targetInfoRenamedFields, each { _, type text })
             )
        else TargetInfoExpanded,

    // -------------------------------------------------------------------------
    // Rename the key column to the generic "value" and attach field/table metadata
    // -------------------------------------------------------------------------
    KeyRenamedToValue = Table.RenameColumns(TargetInfoTyped, {{ sourceTableField, "value" }}),

    WithMetadataColumn = Table.AddColumn(
        KeyRenamedToValue,
        "infoField",
        each [
            source_field = sourceTableField,
            target_field = targetTableField,
            source_table = sourceTableName,
            target_table = targetTableName
        ]
    ),

    // -------------------------------------------------------------------------
    // Expand the metadata record into individual columns and enforce text types
    // -------------------------------------------------------------------------
    MetadataExpanded = fxExpandRecordColumn(WithMetadataColumn, "infoField"),

    // Build the full column list for the empty-table fallback
    EmptyTableColumns =
        { {"value", type text} }
        & List.Transform(sourceInfoFields ?? {}, each {_, type text})
        & List.Transform(targetInfoRenamedFields ?? targetInfoFields ?? {}, each {_, type text})
        & {
            {"source_field", type text},
            {"target_field", type text},
            {"source_table", type text},
            {"target_table", type text}
        },

    Result =
        if Table.IsEmpty(MetadataExpanded)
        then Table.TransformColumnTypes(
                #table(List.Transform(EmptyTableColumns, each _{0}), {}),
                EmptyTableColumns
            )
        else Table.TransformColumnTypes(
                MetadataExpanded,
                {
                    {"source_field", type text},
                    {"target_field", type text},
                    {"source_table", type text},
                    {"target_table", type text}
                }
            )

in
    Result
