//fxGetForeignKeyViolations
(sourceTable as table, targetTable as table, sourceTableName as text, targetTableName as text, sourceTableField as text, targetTableField as text) =>
let
  /*sourceTable = L1_dbo_product_mapping,
  targetTable = dbo_products,
  sourceTableName = "product_mapping",
  targetTableName = "product",
  sourceTableField = "canonical_name",
  targetTableField = "product_name",*/
  #"Merged queries" = Table.NestedJoin(sourceTable, {sourceTableField}, targetTable, {targetTableField}, targetTableName, JoinKind.LeftAnti),
  #"Removed other columns" = Table.SelectColumns(#"Merged queries", {sourceTableField}),
  #"Renamed columns" = Table.RenameColumns(#"Removed other columns", {{sourceTableField, "value"}}),
  #"Added custom" = Table.AddColumn(#"Renamed columns", "field", each targetTableField, type text),
  #"Added custom 1" = Table.AddColumn(#"Added custom", "source_table", each sourceTableName, type text),
  #"Added custom 2" = Table.AddColumn(#"Added custom 1", "target_table", each targetTableName, type text)

in
  #"Added custom 2"
